### PR TITLE
fix(graph): resolve NullPointerException in streaming with tools when streamUsage enabled

### LINKED ISSUE #2702: [BUG] 使用 graph 流式调用带有工具的 LLmNode, 当模型配置了 streamUsage ， 会报空指针异常
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

当我使用 graph 流式调用带有工具的 llm,如果 llm 开始了 include usage 就会报空指针异常：

Image
如果没有开启 include usage 则不会报错

### Expected Behavior

希望正常返回不会报错

### Steps To Reproduce

```java
public static OpenAiChatModel createDashScopeOpenAi(String endpoint, String apiKey) {
        OpenAiApi openAiApi = OpenAiApi.builder()
                .apiKey(apiKey)
                .baseUrl(endpoint)
                .build();
        return OpenAiChatModel.builder()
                .openAiApi(openAiApi)
                .defaultOptions(OpenAiChatOptions.builder()
                        .model("qwen-flash").streamUsage(true).build())
                .toolExecutionEligibilityPredicate(toolExecutionEligibilityPredicate)
                .toolCallingManager(toolCallingManager)
                .build();
    }

public static void main(String[] args) throws GraphStateException, InterruptedException {
        ToolAgentContext.intentTool.put(Intent.date_time_query , ToolCallbacks.from(new DatetimeTool()));
        LlmNode qLlmNode = buildDate(chatClient());
        KeyStrategyFactory keyStrategyFactory = new KeyStrategyFactoryBuilder()
                .addPatternStrategy("session_id", new ReplaceStrategy())
                // 用户输入
                .addPatternStrategy("user_input", new ReplaceStrategy())
                // 闲聊 prompt
                .addPatternStrategy("chat_prompt", new ReplaceStrategy())
                .addPatternStrategy("user_profile", new ReplaceStrategy())
                // 历史上下文
                .addPatternStrategy("messages_history", new ReplaceStrategy())
                .addPatternStrategy("di_id", new ReplaceStrategy())
                .addPatternStrategy("m_id", new ReplaceStrategy())
                .addPatternStrategy("user_input_language", new ReplaceStrategy())
                .addPatternStrategy("user_input_intent", new ReplaceStrategy())
                .addPatternStrategy("chat_reply", new ReplaceStrategy())
                .addPatternStrategy("token_usage", new ReplaceStrategy())
                .build();

        StateGraph stateGraph = new StateGraph("public-chat-flow", keyStrategyFactory);

        stateGraph.addNode("date" , AsyncNodeAction.node_async(qLlmNode));
        stateGraph.addEdge(StateGraph.START , "date");
        stateGraph.addEdge("date" , StateGraph.END);


        Map<String, Object> input = new HashMap<>();
        input.put("session_id", "666");
        input.put("user_input", "北京现在是几点");
        input.put("chat_prompt", PromptReaderUtil.getPrompt("GPT-CHINA"));
        input.put("di_id", 1);
        input.put("mid_", "11");
        CompiledGraph compiledGraph = stateGraph.compile();
        Flux<NodeOutput> nodeOutputFlux = compiledGraph.fluxStream(input, RunnableConfig.builder().build());
        nodeOutputFlux.doOnNext(output -> {
            if (output instanceof StreamingOutput streamingOutput) {
                System.out.println(streamingOutput.chunk());
            }
        }).subscribe();
        Thread.sleep(10000);
    }

    private static ChatClient chatClient() {
        OpenAiChatModel dashScopeOpenAi = DashScopeOpenAiCreator.createDashScopeOpenAi("https://dashscope.aliyuncs.com/compatible-mode", "xxxx");
        return ChatClient.builder(dashScopeOpenAi).build();
    }
public static LlmNode buildDate(ChatClient chatClient) {
        return LlmNode.builder()
                .chatClient(chatClient)
                .systemPromptTemplate(PromptReaderUtil.getPrompt("tool_agent/date_agent"))
                .userPromptTemplateKey("user_input")
                .messagesKey("messages_history")
                .toolCallbacks(Arrays.stream(ToolAgentContext.intentTool.get(Intent.date_time_query)).toList())
                .outputKey("chat_reply")
                .stream(true)
                .build();
    }
```

### Environment

```markdown
Spring AI Alibaba version(s):1.0.0.4
```

### Debug logs

报错位置：com/alibaba/cloud/ai/spring-ai-alibaba-graph-core/1.0.0.4/spring-ai-alibaba-graph-core-1.0.0.4-sources.jar!/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java:177

Image
是否把response.getResult()的判空提前到 lastResponse 的判空前

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JGoP-L**
Fixes #2702
1. Why multiple layers of null checks?
   - Filter at line 189-195: Catches null results early in the stream
   - Null check at line 198-200: Defensive programming for edge cases that pass the filter
   - Null check at line 220-222: Protects against null in lastResponse (from AtomicReference)
   - Filter at line 264: Final cleanup to ensure no null values leak downstream
   
   This defense-in-depth approach ensures robustness in all scenarios.

2. Why does the test show chunk=null in output?
   This is expected and correct. StreamingOutput explicitly allows null chunks (see StreamingOutput.java line 25 comment). The test output shows:
   StreamingOutput{chunk=null}  ← This is the usage-only chunk, correctly handled

3. Why is there a Jackson serialization error in test output?
   This is unrelated to Issue #2702. It's a separate issue with serializing java.time.Duration in ChatResponseMetadata. The important part is that no NPE occurs, which is what this fix addresses.

4. Pattern consistency
   This fix follows the same pattern already used in StreamingChatGenerator.java line 151:
   .filter(response -> response.getResult() != null && response.getResult().getOutput() != null)

5. Test coverage
   ✅ Reproduces the exact bug scenario (usage-only chunks with null results)
   ✅ Uses framework-standard components (LLmNodeAction, StateGraph)
   ✅ Verifies streaming completes without NPE
   ✅ Includes comprehensive JavaDoc explaining the issue and solution

6. No breaking changes
   ✅ All 155 existing tests pass
   ✅ Normal ChatResponse objects (with non-null results) are unaffected
   ✅ Only filters out invalid usage-only chunks
   ✅ No API changes, purely internal defensive programming

Files changed:
- spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java (+14 lines)
- spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/GraphFluxGenerator.java (+40 lines)
- spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/Issue2702ReproductionTest.java (+174 lines, new file)

Total: 3 files changed, 215 insertions(+), 13 deletions(-)

### CODE REVIEW

**Comment by JGoP-L** [comment]
@zxuexingzhijie  ptal, thx

File: spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java [hunk 1]
```diff
@@ -193,6 +194,11 @@ private Optional<Flux<GraphResponse<NodeOutput>>> getEmbedFlux(GraphRunnerContex
                 return true;
             }).map(element -> {
 				if (element instanceof ChatResponse response) {
+					// Additional null check for response.getResult()
+					if (response.getResult() == null) {
```
Comment (disaster1-tesk) [inline spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: llmNode already uses graphflux to handle the stream, so it shouldn't need to be changed here

Comment (JGoP-L) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: > llmNode already uses graphflux to handle the stream, so it shouldn't need to be changed here

OK，我已经移除了不必要的修改。在测试中发现了新的问题：1.Duration ，nvalidDefinitionException: Java 8 date/time type Duration not supported，修复：在 ObjectMapper 中注册 JavaTimeModule
2.ChatResponse 序列化失败，InvalidDefinitionException: Cannot construct instance of ChatResponse，修复：序列化时将 ChatResponse 转换为 Map，修复：反序列化时返回 null（ChatResponse 无法重建）。我已经提交到当前pr，如果你认为有必要分开，我可以重新拆分独立的pr

Comment (disaster1-tesk) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: 需要单独处理提一个pr上来，每一个pr尽可能保证是原子的

Comment (JGoP-L) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: ok

Comment (JGoP-L) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: > 需要单独处理提一个pr上来，每一个pr尽可能保证是原子的
当前分支是只处理了npe。
https://github.com/alibaba/spring-ai-alibaba/pull/3068  这个分支处理了序列化问题

Comment (JGoP-L) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java]: @disaster1-tesk  hi，bro，look look
