### PR TITLE
fix(agent): ensure that the maxConcurrency function of ParallelAgent is implemented.

### LINKED ISSUE #3998: [BUG] The maxConcurrency config in ParallelAgent isn't working
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

There is a maxConcurrency in ParallelAgent. Normally, it's a param to limit the concurrency of this node/agent.  Although the maxConcurrency is passed to ParallelGraphBuildingStrategy/EnhancedParallelResultAggregator, etc, but after reviewing the code, maxConcurrency isn't used to limit.

### Expected Behavior

ParallelAgent can consume the maxConcurrency config, and limit the concurrency.

### Steps To Reproduce

_No response_

### Environment

```markdown
Spring AI Alibaba version(s):1.1.0.0-RC2
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maple525866**
### Describe what this PR does / why we need it
1.问题描述
经过测试与代码审查发现，虽然maxConcurrency 字段已定义，且确实被传递到了被传递到多个类，但是并没有被启用来进行并行限制功能。

未修改前，真正的并行执行发生在 `ParallelNode.AsyncParallelNodeAction.apply()` 方法中，该方法：
- 一次性提交所有子任务到线程池
- 完全不知道 `maxConcurrency` 的存在
- 缺少从 ParallelAgent 到 ParallelNode 的配置传递机制

### Does this pull request fix one issue?
fixes #3998 

### Describe how you did it
2.我采用了信号量（Semaphore）配合 RunnableConfig 传递配置的方案：
- 精确控制并发，不创建额外线程池
- 复用现有 Executor，资源利用率高
- 通过 RunnableConfig metadata 传递配置，架构清晰
- 向后兼容，不影响现有功能，原来的无限制场景得到保证

### Describe how to verify it
3.添加了相关场景的单测，mvn clean test即可

### CODE REVIEW

**Comment by chickenlj** [comment]
Please solve the conflicts. Thanks.

**Comment by maple525866** [comment]
> Please solve the conflicts. Thanks.

done ❤️

File: spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java [hunk 1]
```diff
@@ -361,8 +376,74 @@ private CompletableFuture<Map<String, Object>> waitForFirstSuccessful(
...
 		@Override
 		public CompletableFuture<Map<String, Object>> apply(OverAllState state, RunnableConfig config) {
+			// Get maxConcurrency from config metadata
+			Integer maxConcurrency = config.metadata(formatMaxConcurrencyKey(nodeId))
+					.filter(value -> value instanceof Integer)
+					.map(Integer.class::cast)
+					.orElse(null);
+
+			// Create semaphore for concurrency control if maxConcurrency is set
+			Semaphore semaphore = maxConcurrency != null ? new Semaphore(maxConcurrency) : null;
```
Comment (yuluo-yx) [inline spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java:439]: only for reference:

```
  Semaphore semaphore = config.metadata(formatMaxConcurrencyKey(nodeId))
          .filter(value -> value instanceof Integer)
          .map(Integer.class::cast)
          .map(Semaphore::new)
          .orElse(null);
```

File: spring-ai-alibaba-agent-framework/src/main/java/com/alibaba/cloud/ai/graph/agent/flow/node/EnhancedParallelResultAggregator.java [hunk 2]
```diff
@@ -96,7 +96,13 @@ public Map<String, Object> apply(OverAllState state) throws Exception {
...
 		}
 
-		result.put(outputKey, finalResult);
+		// Only add the merged result if outputKey is not null
+		if (outputKey != null && !outputKey.trim().isEmpty()) {
+			result.put(outputKey, finalResult);
+			logger.debug("Enhanced result aggregation completed. Final result stored under key: {}", outputKey);
+		} else {
+			logger.debug("Enhanced result aggregation completed. No outputKey specified, skipping merged result storage.");
+		}
```
Comment (maple525866) [inline spring-ai-alibaba-agent-framework/src/main/java/com/alibaba/cloud/ai/graph/agent/flow/node/EnhancedParallelResultAggregator.java:105]: While fixing the CI issue in the `test` function, I discovered that `EnhancedParallelResultAggregator` was still executing `result.put(outputKey, finalResult)` even when `outputKey` was null, causing JSON serialization to fail.

I added a null check to ensure correct serialization.

File: spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java (hunk 1 above)
Comment (maple525866) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java:439]: Received, I will check it.

File: spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java [hunk 3]
```diff
@@ -361,8 +376,74 @@ private CompletableFuture<Map<String, Object>> waitForFirstSuccessful(
...
+
+			if (semaphore != null) {
+				logger.info("Parallel node {} will execute with max concurrency: {}", nodeId, maxConcurrency);
```
Comment (maple525866) [inline spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java:442]: The reason for keeping the `maxConcurrency` variable here is for convenience in logging. If it's not needed, I agree with the following code: 
@yuluo-yx 
```java
  Semaphore semaphore = config.metadata(formatMaxConcurrencyKey(nodeId))
          .filter(value -> value instanceof Integer)
          .map(Integer.class::cast)
          .map(Semaphore::new)
          .orElse(null);
```

Comment (yuluo-yx) [reply spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java:442]: got, keep it, more logs can provide insights into system operating status.
