### PR TITLE
fix(memories): fix chat message media serializer exception

### LINKED ISSUE #2305: [BUG] JedisRedisChatMemoryRepository message media 序列化异常
### Is there an existing issue for this?

- [x] I have searched the existing issues

### **异常描述：**

使用 JedisRedisChatMemoryRepository 实现对话记忆的功能，在使用视觉多模态模型(Vision)时，
Media 对象序列化失败：当 data 不是 byte[] 时，会抛出 JsonMappingException

### 原因：
- Media#getDataAsByteArray() 仅在 data 为 byte[] 时才能返回成功，否则会抛出 IllegalStateException。
- Jackson 在序列化 Media 时会自动调用 getDataAsByteArray()（因为属性名匹配），导致抛出异常。

**异常如下:**
```
ERROR o.springframework.ai.chat.model.MessageAggregator - Aggregation Error
java.lang.RuntimeException: Error serializing message
	at com.alibaba.cloud.ai.memory.redis.BaseRedisChatMemoryRepository.serializeMessage(BaseRedisChatMemoryRepository.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at com.alibaba.cloud.ai.memory.redis.JedisRedisChatMemoryRepository.saveAll(JedisRedisChatMemoryRepository.java:198)
	at org.springframework.ai.chat.memory.MessageWindowChatMemory.add(MessageWindowChatMemory.java:65)
	at org.springframework.ai.chat.memory.ChatMemory.add(ChatMemory.java:46)
	at org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor.before(MessageChatMemoryAdvisor.java:96)
	at org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor.lambda$adviseStream$1(MessageChatMemoryAdvisor.java:125)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Media data is not a byte[] (through reference chain: org.springframework.ai.chat.messages.UserMessage["media"]->java.util.ArrayList[0]->org.springframework.ai.content.Media["dataAsByteArray"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:401)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4811)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4052)
	at com.alibaba.cloud.ai.memory.redis.BaseRedisChatMemoryRepository.serializeMessage(BaseRedisChatMemoryRepository.java:60)
	... 24 common frames omitted
Caused by: java.lang.IllegalStateException: Media data is not a byte[]
	at org.springframework.ai.content.Media.getDataAsByteArray(Media.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	... 36 common frames omitted
```

### 我的临时解决方案
```java
public class MessageSerializer extends JsonSerializer<Message> {
    @Override
    public void serialize(Message value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
        gen.writeStartObject();
        gen.writeStringField("messageType", value.getMessageType().name());
        gen.writeObjectField("metadata", value.getMetadata());
        gen.writeStringField("text", value.getText());
        // 不输出 media
        gen.writeEndObject();
    }
}
```

### Expected Behavior

_No response_

### Steps To Reproduce

最小复现步骤
```java
@Test
void shouldSerializeUserMessageWithUriMedia() throws JsonProcessingException {
    var userMessage = UserMessage.builder()
        .text("Explain what do you see on this picture?")
        .media(List.of(Media.builder()
            .mimeType(MimeTypeUtils.IMAGE_PNG)
            .data(URI.create("https://docs.spring.io/spring-ai/reference/_images/multimodal.test.png"))
            .build()))
        .build();
    new ObjectMapper().writeValueAsString(userMessage);
}
```

### Environment

```markdown
Spring AI Alibaba version(s):1.0.0.3
Spring AI version 1.0.1
JDK: 17
Redis client: Jedis
```

### Debug logs

ERROR o.springframework.ai.chat.model.MessageAggregator - Aggregation Error
java.lang.RuntimeException: Error serializing message
	at com.alibaba.cloud.ai.memory.redis.BaseRedisChatMemoryRepository.serializeMessage(BaseRedisChatMemoryRepository.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at com.alibaba.cloud.ai.memory.redis.JedisRedisChatMemoryRepository.saveAll(JedisRedisChatMemoryRepository.java:198)
	at org.springframework.ai.chat.memory.MessageWindowChatMemory.add(MessageWindowChatMemory.java:65)
	at org.springframework.ai.chat.memory.ChatMemory.add(ChatMemory.java:46)
	at org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor.before(MessageChatMemoryAdvisor.java:96)
	at org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor.lambda$adviseStream$1(MessageChatMemoryAdvisor.java:125)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Media data is not a byte[] (through reference chain: org.springframework.ai.chat.messages.UserMessage["media"]->java.util.ArrayList[0]->org.springframework.ai.content.Media["dataAsByteArray"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:401)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4811)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4052)
	at com.alibaba.cloud.ai.memory.redis.BaseRedisChatMemoryRepository.serializeMessage(BaseRedisChatMemoryRepository.java:60)
	... 24 common frames omitted
Caused by: java.lang.IllegalStateException: Media data is not a byte[]
	at org.springframework.ai.content.Media.getDataAsByteArray(Media.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	... 36 common frames omitted

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by benym**
### Describe what this PR does / why we need it
Because jackson default behavior serializes method names with `get` or `is`, for `Message`, its subclass `UserMessage` contains a `media` field, which is a list composed of `Media` objects. The `Media` contains the `getDataAsByteArray` method, which is used to handle different types of `data` attributes. When the `data` attribute is not `byte[]`, an `IllegalStateException` will be thrown. A similar method also exists in the sub-attribute `MimeType` of `Media`. Such as `org.springframework.util.MimeType#isWildcardType`, but usually for memory, the serialization of property field method has no meaning

### Does this pull request fix one issue?

fix #2305 

### Describe how you did it

Since the `Media` object is controlled by the official `spring-ai` repository, using a custom `Media` serializer is not a good approach. To adapt to subsequent changes in `Media` versions, I set the default behavior of the objectMapper to ignore the serialization of `get` and `is` methods that are meaningless to the memory module. And it allows all fields in the class and their corresponding `get/set` methods to be automatically detected

### Describe how to verify it
PixPin_2025-09-02_22-45-49

### Special notes for reviews
@VLSMB

### CODE REVIEW

**Comment by VLSMB** [comment]
Hello, I ran the unit test locally and found that it failed. The issue seems to be an error during the deserialization of `Message`, likely caused by the change in the `ObjectMapper`'s serialization configuration to use fields, which altered the keys in the resulting JSON. Therefore, the implementation of `MessageDeserializer` should be modified accordingly. Additionally, you need to rename the unit test class to end with "Test" or adjust the relevant configuration to ensure the CI can run the tests properly. Furthermore, the `MessageDeserializer` currently lacks code to deserialize the Media field, resulting in its absence after deserialization. It may be necessary to implement corresponding constructors for each type of `Message`.

image

image

**Comment by VLSMB** [comment]
In addition to the `Media `field in `UserMessage`, `AssistantMessage` also contains ToolCall-related information. I think we can define four private methods to construct the corresponding messages, with the method signatures as `Message buildxxxMessage(JsonNode node)`.

**Comment by benym** [comment]
I'm currently checking the historical commits of MessageDeserializer. I found that the initial implementation of #508 handled Media, but after #803, this code was refactored and the handling of Media was removed. Is it because of some problem? I'm a bit confused

**Comment by benym** [comment]
In addition, after the global search of MessageDeserializer, the same MessageDeserializer code as in redis memory also exists in `deepsearch` and `Memcached`. I think they may also encounter the same problem for serialization. Including #2275 handled last week, `com.alibaba.cloud.ai.graph.serializer.plain_text.jackson.JacksonStateSerializer#registerSpringAIMessageModule`, whether are common problems. If it is a common issue, I think the serialization of the corresponding Message can be considered as a separate package in the future

**Comment by VLSMB** [comment]
Hello, I've given it some thought and feel that the `Media` object really shouldn't be saved or read, as its internal `byte[]` may consume significant memory resources. Moreover, `Media` resources are primarily important only when first sent to the LLM and are likely less critical as historical messages. Therefore, you just need to ensure that no errors occur with the `Media` field when saving Messages. However, these `MessageDeserializer` have all overlooked the handling of `ToolResponseMessage`. Please address the redis part first, and we can deal with other memory issues later.

**Comment by benym** [comment]
> Hello, I've given it some thought and feel that the `Media` object really shouldn't be saved or read, as its internal `byte[]` may consume significant memory resources. Moreover, `Media` resources are primarily important only when first sent to the LLM and are likely less critical as historical messages. Therefore, you just need to ensure that no errors occur with the `Media` field when saving Messages. However, these `MessageDeserializer` have all overlooked the handling of `ToolResponseMessage`. Please address the redis part first, and we can deal with other memory issues later.

I agree, and I found that Media itself doesn't provide an empty constructor for creation, which is usually quite troublesome for serialization behavior. I'm currently dealing with metadata, toolcall, and ToolResponseMessage, and I'll finish providing the code later

**Comment by benym** [comment]
> I'm currently checking the historical commits of MessageDeserializer. I found that the initial implementation of #508 handled Media, but after #803, this code was refactored and the handling of Media was removed. Is it because of some problem? I'm a bit confused

The multi-parameter constructors of UserMessage and SystemMessage are both private. Therefore, the serialization method using jackson at that time could not be deserialized. I think this is also the reason for the modification of #803 pr. The simplest new construction was adopted, which led to the loss of the remaining parameters. But in fact, it can be constructed through the built-in builder

**Comment by benym** [comment]
@VLSMB hello，I have already finished. The test result is
image
image
image
image
image
image
image

File: community/memories/spring-ai-alibaba-starter-memory-redis/src/test/java/com/alibaba/cloud/ai/memory/redis/serializer/MediaSerializerTest.java [hunk 1]
```diff
@@ -0,0 +1,235 @@
...
+		public String getWeather(@ToolParam(description = "城市名称") String city,
+				@ToolParam(description = "当前时间戳") String currentTimestamp) {
+			logger.info("WeatherTool invoked with city: {}, timestamp: {}", city, currentTimestamp);
+			return String.format("{\"city\": \"%s\", \"temperature\": -50, \"time\": \"%s\"}", city, currentTimestamp);
+		}
+
+	}
+
+	@Test
+	public void should_serializeSuccess_when_serializeMessage_given_stringData() {
```
Comment (VLSMB) [inline community/memories/spring-ai-alibaba-starter-memory-redis/src/test/java/com/alibaba/cloud/ai/memory/redis/serializer/MediaSerializerTest.java]: Please use camelCase naming here, and shorten the method name.

Comment (benym) [reply community/memories/spring-ai-alibaba-starter-memory-redis/src/test/java/com/alibaba/cloud/ai/memory/redis/serializer/MediaSerializerTest.java]: done
